# NETTOYAGE DES DONNÉES DES VOITURES

Importation de la bibliothèque Pandas

In [3]:
import pandas as pd

Charger les données depuis un fichier CSV sur une DataFrame

In [5]:
df = pd.read_csv('avito_car_dataset_ALL.csv')

In [6]:
df

,Unnamed: 0,Lien,Ville,Secteur,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,0,https://www.avito.ma/fr/massira_2/voitures/FIA...,Temara,Massira 2,Fiat,Punto,2007,200 000 - 249 999,Diesel,5,...,False,False,True,False,False,False,True,False,False,60000
1,1,https://www.avito.ma/fr/temara/voitures/Dacia_...,Temara,NaN,Dacia,Dokker Van,2013,400 000 - 449 999,Diesel,6,...,False,False,False,False,False,False,False,False,False,70000
2,2,https://www.avito.ma/fr/casablanca/voitures/Da...,Casablanca,NaN,Dacia,Dokker,2014,160 000 - 169 999,Diesel,6,...,False,False,False,False,False,False,False,False,False,90000
3,3,https://www.avito.ma/fr/casablanca/voitures/to...,Casablanca,NaN,Volkswagen,Touareg,2005,0 - 4 999,Diesel,10,...,False,False,False,False,False,False,False,False,False,90000
4,4,https://www.avito.ma/fr/dakhla/voitures/Toyota...,Dakhla,NaN,Toyota,Prado,2007,200 000 - 249 999,Diesel,12,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,24771,https://www.avito.ma/fr/gueliz/voitures/Mini_C...,Marrakech,Guéliz,mini,cabrio,2011,70 000 - 74 999,Essence,9,...,False,False,True,True,False,False,False,False,False,180000
24772,24772,https://www.avito.ma/fr/safi/voitures/mini_coo...,Safi,NaN,mini,cooper,2007,190 000 - 199 999,Essence,9,...,False,False,True,True,False,False,True,False,False,63000
24773,24773,https://www.avito.ma/fr/sal%C3%A9/voitures/Min...,Salé,NaN,mini,one,2006,10 000 - 14 999,Essence,8,...,False,False,True,False,False,False,True,False,False,60000
24774,24774,https://www.avito.ma/fr/polo/voitures/Mini_coo...,Casablanca,Polo,mini,cooper,2010,140 000 - 149 999,Essence,9,...,False,False,True,True,False,False,True,False,False,85000
24775,24775,https://www.avito.ma/fr/marrakech/voitures/min...,Marrakech,NaN,mini,cooper,2008,180 000 - 189 999,Essence,9,...,False,False,False,False,False,False,False,False,False,84000

Voir les informations des lignes de la DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24776 entries, 0 to 24775
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Unnamed: 0                          24776 non-null  int64
 1   Lien                                24776 non-null  object
 2   Ville                               24776 non-null  object
 3   Secteur                             10810 non-null  object
 4   Marque                              24776 non-null  object
 5   Modéle                              24776 non-null  object
 6   Année-Modele                        24776 non-null  int64
 7   Kilométrage                         24776 non-null  object
 8   Type de carburant                   24776 non-null  object
 9   Puissance fiscale                   24776 non-null  int64
 10  Boite de vitesses                   24776 non-null  object
 11  Nombre de portes                    20396 non-null  float64
 12  Origine                             19489 non-null  object
 13  Premiére main                       18567 non-null  object
 14  état                                18098 non-null  object
 15  Jantes aluminium                    24776 non-null  bool
 16  Airbags                             24776 non-null  bool
 17  Climatisation                       24776 non-null  bool
 18  Systéme de navigation/GPS           24776 non-null  bool
 19  Toit ouvrant                        24776 non-null  bool
 20  Siéges cuir                         24776 non-null  bool
 21  Radar de recul                      24776 non-null  bool
 22  Caméra de recul                     24776 non-null  bool
 23  Vitres électriques                  24776 non-null  bool
 24  ABS                                 24776 non-null  bool
 25  ESP                                 24776 non-null  bool
 26  Régulateur de vitesse               24776 non-null  bool
 27  Limiteur de vitesse                 24776 non-null  bool
 28  CD/MP3/Bluetooth                    24776 non-null  bool
 29  Ordinateur de bord                  24776 non-null  bool
 30  Verrouillage centralisé é distance  24776 non-null  bool
 31  Prix                                24776 non-null  int64
dtypes: bool(16), float64(1), int64(4), object(11)
memory usage: 3.4+ MB

Supprimer les colonnes non nécessaires

In [10]:
df.drop(['Unnamed: 0','Lien','Ville' ,	'Secteur'],axis=1,inplace=True)

In [11]:
df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,Fiat,Punto,2007,200 000 - 249 999,Diesel,5,Manuelle,5.0,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
1,Dacia,Dokker Van,2013,400 000 - 449 999,Diesel,6,Manuelle,3.0,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,70000
2,Dacia,Dokker,2014,160 000 - 169 999,Diesel,6,Manuelle,5.0,WW au Maroc,NaN,...,False,False,False,False,False,False,False,False,False,90000
3,Volkswagen,Touareg,2005,0 - 4 999,Diesel,10,Automatique,5.0,WW au Maroc,Oui,...,False,False,False,False,False,False,False,False,False,90000
4,Toyota,Prado,2007,200 000 - 249 999,Diesel,12,Manuelle,5.0,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,70 000 - 74 999,Essence,9,Manuelle,3.0,WW au Maroc,Oui,...,False,False,True,True,False,False,False,False,False,180000
24772,mini,cooper,2007,190 000 - 199 999,Essence,9,Manuelle,3.0,WW au Maroc,Non,...,False,False,True,True,False,False,True,False,False,63000
24773,mini,one,2006,10 000 - 14 999,Essence,8,Manuelle,3.0,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
24774,mini,cooper,2010,140 000 - 149 999,Essence,9,Automatique,3.0,Dédouanée,NaN,...,False,False,True,True,False,False,True,False,False,85000
24775,mini,cooper,2008,180 000 - 189 999,Essence,9,Manuelle,NaN,Importée neuve,Non,...,False,False,False,False,False,False,False,False,False,84000

Voir les données manquantes

In [13]:
df.isnull().sum()

Marque                                   0
Modéle                                   0
Année-Modele                             0
Kilométrage                              0
Type de carburant                        0
Puissance fiscale                        0
Boite de vitesses                        0
Nombre de portes                      4380
Origine                               5287
Premiére main                         6209
état                                  6678
Jantes aluminium                         0
Airbags                                  0
Climatisation                            0
Systéme de navigation/GPS                0
Toit ouvrant                             0
Siéges cuir                              0
Radar de recul                           0
Caméra de recul                          0
Vitres électriques                       0
ABS                                      0
ESP                                      0
Régulateur de vitesse                    0
Limiteur de vitesse                      0
CD/MP3/Bluetooth                         0
Ordinateur de bord                       0
Verrouillage centralisé é distance       0
Prix                                     0
dtype: int64

on a des valeur manquantes dans les colonne Nombre de portes ,Origine ,Premiére main ,et état

Remplacer les données manquantes dans la colonne 'Nombre de portes' par la moyenne des valeurs existantes

In [15]:
df['Nombre de portes'].fillna(df['Nombre de portes'].mode()[0],inplace=True)
df['Nombre de portes']=df['Nombre de portes'].astype(int)
df

C:\Users\HP\AppData\Local\Temp\ipykernel_19728\2260916797.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Nombre de portes'].fillna(df['Nombre de portes'].mode()[0],inplace=True)

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,Fiat,Punto,2007,200 000 - 249 999,Diesel,5,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
1,Dacia,Dokker Van,2013,400 000 - 449 999,Diesel,6,Manuelle,3,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,70000
2,Dacia,Dokker,2014,160 000 - 169 999,Diesel,6,Manuelle,5,WW au Maroc,NaN,...,False,False,False,False,False,False,False,False,False,90000
3,Volkswagen,Touareg,2005,0 - 4 999,Diesel,10,Automatique,5,WW au Maroc,Oui,...,False,False,False,False,False,False,False,False,False,90000
4,Toyota,Prado,2007,200 000 - 249 999,Diesel,12,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,70 000 - 74 999,Essence,9,Manuelle,3,WW au Maroc,Oui,...,False,False,True,True,False,False,False,False,False,180000
24772,mini,cooper,2007,190 000 - 199 999,Essence,9,Manuelle,3,WW au Maroc,Non,...,False,False,True,True,False,False,True,False,False,63000
24773,mini,one,2006,10 000 - 14 999,Essence,8,Manuelle,3,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
24774,mini,cooper,2010,140 000 - 149 999,Essence,9,Automatique,3,Dédouanée,NaN,...,False,False,True,True,False,False,True,False,False,85000
24775,mini,cooper,2008,180 000 - 189 999,Essence,9,Manuelle,5,Importée neuve,Non,...,False,False,False,False,False,False,False,False,False,84000

In [16]:
not_complete_columns = ['Origine','Premiére main','état']
for c in not_complete_columns:
    df[c].fillna(df[c].mode()[0], inplace=True)
df

C:\Users\HP\AppData\Local\Temp\ipykernel_19728\3622267160.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[c].fillna(df[c].mode()[0], inplace=True)

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,Fiat,Punto,2007,200 000 - 249 999,Diesel,5,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
1,Dacia,Dokker Van,2013,400 000 - 449 999,Diesel,6,Manuelle,3,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,70000
2,Dacia,Dokker,2014,160 000 - 169 999,Diesel,6,Manuelle,5,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,90000
3,Volkswagen,Touareg,2005,0 - 4 999,Diesel,10,Automatique,5,WW au Maroc,Oui,...,False,False,False,False,False,False,False,False,False,90000
4,Toyota,Prado,2007,200 000 - 249 999,Diesel,12,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,70 000 - 74 999,Essence,9,Manuelle,3,WW au Maroc,Oui,...,False,False,True,True,False,False,False,False,False,180000
24772,mini,cooper,2007,190 000 - 199 999,Essence,9,Manuelle,3,WW au Maroc,Non,...,False,False,True,True,False,False,True,False,False,63000
24773,mini,one,2006,10 000 - 14 999,Essence,8,Manuelle,3,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
24774,mini,cooper,2010,140 000 - 149 999,Essence,9,Automatique,3,Dédouanée,Non,...,False,False,True,True,False,False,True,False,False,85000
24775,mini,cooper,2008,180 000 - 189 999,Essence,9,Manuelle,5,Importée neuve,Non,...,False,False,False,False,False,False,False,False,False,84000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24776 entries, 0 to 24775
Data columns (total 28 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Marque                              24776 non-null  object
 1   Modéle                              24776 non-null  object
 2   Année-Modele                        24776 non-null  int64
 3   Kilométrage                         24776 non-null  object
 4   Type de carburant                   24776 non-null  object
 5   Puissance fiscale                   24776 non-null  int64
 6   Boite de vitesses                   24776 non-null  object
 7   Nombre de portes                    24776 non-null  int32
 8   Origine                             24776 non-null  object
 9   Premiére main                       24776 non-null  object
 10  état                                24776 non-null  object
 11  Jantes aluminium                    24776 non-null  bool
 12  Airbags                             24776 non-null  bool
 13  Climatisation                       24776 non-null  bool
 14  Systéme de navigation/GPS           24776 non-null  bool
 15  Toit ouvrant                        24776 non-null  bool
 16  Siéges cuir                         24776 non-null  bool
 17  Radar de recul                      24776 non-null  bool
 18  Caméra de recul                     24776 non-null  bool
 19  Vitres électriques                  24776 non-null  bool
 20  ABS                                 24776 non-null  bool
 21  ESP                                 24776 non-null  bool
 22  Régulateur de vitesse               24776 non-null  bool
 23  Limiteur de vitesse                 24776 non-null  bool
 24  CD/MP3/Bluetooth                    24776 non-null  bool
 25  Ordinateur de bord                  24776 non-null  bool
 26  Verrouillage centralisé é distance  24776 non-null  bool
 27  Prix                                24776 non-null  int64
dtypes: bool(16), int32(1), int64(3), object(8)
memory usage: 2.6+ MB

Voir les données manquantes une autre fois pour vérifier qu'il n'y a aucune donnée manquante

In [19]:
df.isnull().sum()

Marque                                0
Modéle                                0
Année-Modele                          0
Kilométrage                           0
Type de carburant                     0
Puissance fiscale                     0
Boite de vitesses                     0
Nombre de portes                      0
Origine                               0
Premiére main                         0
état                                  0
Jantes aluminium                      0
Airbags                               0
Climatisation                         0
Systéme de navigation/GPS             0
Toit ouvrant                          0
Siéges cuir                           0
Radar de recul                        0
Caméra de recul                       0
Vitres électriques                    0
ABS                                   0
ESP                                   0
Régulateur de vitesse                 0
Limiteur de vitesse                   0
CD/MP3/Bluetooth                      0
Ordinateur de bord                    0
Verrouillage centralisé é distance    0
Prix                                  0
dtype: int64

Voir les statistiques de la DataFrame

In [21]:
df.describe()

       Année-Modele  Puissance fiscale  Nombre de portes          Prix
count  24776.000000       24776.000000      24776.000000  2.477600e+04
mean    2011.844244           7.193938          4.922425  2.169588e+05
std        5.462925           1.574124          0.386184  6.749569e+06
min     1990.000000           5.000000          3.000000  6.000000e+04
25%     2008.000000           6.000000          5.000000  7.500000e+04
50%     2013.000000           7.000000          5.000000  1.000000e+05
75%     2016.000000           8.000000          5.000000  1.400000e+05
max     2022.000000          14.000000          5.000000  6.120372e+08

In [22]:
df.head()

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,Fiat,Punto,2007,200 000 - 249 999,Diesel,5,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
1,Dacia,Dokker Van,2013,400 000 - 449 999,Diesel,6,Manuelle,3,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,70000
2,Dacia,Dokker,2014,160 000 - 169 999,Diesel,6,Manuelle,5,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,90000
3,Volkswagen,Touareg,2005,0 - 4 999,Diesel,10,Automatique,5,WW au Maroc,Oui,...,False,False,False,False,False,False,False,False,False,90000
4,Toyota,Prado,2007,200 000 - 249 999,Diesel,12,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,97000

Transformer le kilométrage de la gamme en point médian

In [24]:
df['Kilométrage'] = df['Kilométrage'].str.replace(' ', '')
df[['Kilométrage_Min', 'Kilométrage_Max']] = df['Kilométrage'].str.extract('(\d+)-(\d+)', expand=True).astype(int)
df['Kilométrage']=(df['Kilométrage_Min']+df['Kilométrage_Max']+1)/2
df['Kilométrage']=df['Kilométrage'].astype(int)
df = df.drop(['Kilométrage_Min', 'Kilométrage_Max'], axis=1)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\HP\AppData\Local\Temp\ipykernel_19728\1341969006.py:2: SyntaxWarning: invalid escape sequence '\d'
  df[['Kilométrage_Min', 'Kilométrage_Max']] = df['Kilométrage'].str.extract('(\d+)-(\d+)', expand=True).astype(int)

In [25]:
df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,Fiat,Punto,2007,225000,Diesel,5,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
1,Dacia,Dokker Van,2013,425000,Diesel,6,Manuelle,3,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,70000
2,Dacia,Dokker,2014,165000,Diesel,6,Manuelle,5,WW au Maroc,Non,...,False,False,False,False,False,False,False,False,False,90000
3,Volkswagen,Touareg,2005,2500,Diesel,10,Automatique,5,WW au Maroc,Oui,...,False,False,False,False,False,False,False,False,False,90000
4,Toyota,Prado,2007,225000,Diesel,12,Manuelle,5,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,Essence,9,Manuelle,3,WW au Maroc,Oui,...,False,False,True,True,False,False,False,False,False,180000
24772,mini,cooper,2007,195000,Essence,9,Manuelle,3,WW au Maroc,Non,...,False,False,True,True,False,False,True,False,False,63000
24773,mini,one,2006,12500,Essence,8,Manuelle,3,WW au Maroc,Non,...,False,False,True,False,False,False,True,False,False,60000
24774,mini,cooper,2010,145000,Essence,9,Automatique,3,Dédouanée,Non,...,False,False,True,True,False,False,True,False,False,85000
24775,mini,cooper,2008,185000,Essence,9,Manuelle,5,Importée neuve,Non,...,False,False,False,False,False,False,False,False,False,84000

Unification des données : transformer toutes les valeurs en minuscules et enlever les accents

In [27]:
string_columns=['Modéle','Marque','Type de carburant','Boite de vitesses','Origine','Premiére main','état']
for column in string_columns:
    df[column] = df[column].str.lower().str.strip()
    df[column] = df[column].str.replace('é','e')

df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,fiat,punto,2007,225000,diesel,5,manuelle,5,ww au maroc,non,...,False,False,True,False,False,False,True,False,False,60000
1,dacia,dokker van,2013,425000,diesel,6,manuelle,3,ww au maroc,non,...,False,False,False,False,False,False,False,False,False,70000
2,dacia,dokker,2014,165000,diesel,6,manuelle,5,ww au maroc,non,...,False,False,False,False,False,False,False,False,False,90000
3,volkswagen,touareg,2005,2500,diesel,10,automatique,5,ww au maroc,oui,...,False,False,False,False,False,False,False,False,False,90000
4,toyota,prado,2007,225000,diesel,12,manuelle,5,ww au maroc,non,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,essence,9,manuelle,3,ww au maroc,oui,...,False,False,True,True,False,False,False,False,False,180000
24772,mini,cooper,2007,195000,essence,9,manuelle,3,ww au maroc,non,...,False,False,True,True,False,False,True,False,False,63000
24773,mini,one,2006,12500,essence,8,manuelle,3,ww au maroc,non,...,False,False,True,False,False,False,True,False,False,60000
24774,mini,cooper,2010,145000,essence,9,automatique,3,dedouanee,non,...,False,False,True,True,False,False,True,False,False,85000
24775,mini,cooper,2008,185000,essence,9,manuelle,5,importee neuve,non,...,False,False,False,False,False,False,False,False,False,84000

In [28]:
df.describe()

,Année-Modele,Kilométrage,Puissance fiscale,Nombre de portes,Prix
count,24776.000000,24776.000000,24776.000000,24776.000000,2.477600e+04
mean,2011.844244,133035.699871,7.193938,4.922425,2.169588e+05
std,5.462925,89088.887159,1.574124,0.386184,6.749569e+06
min,1990.000000,2500.000000,5.000000,3.000000,6.000000e+04
25%,2008.000000,62500.000000,6.000000,5.000000,7.500000e+04
50%,2013.000000,125000.000000,7.000000,5.000000,1.000000e+05
75%,2016.000000,195000.000000,8.000000,5.000000,1.400000e+05
max,2022.000000,475000.000000,14.000000,5.000000,6.120372e+08

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24776 entries, 0 to 24775
Data columns (total 28 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Marque                              24776 non-null  object
 1   Modéle                              24776 non-null  object
 2   Année-Modele                        24776 non-null  int64
 3   Kilométrage                         24776 non-null  int32
 4   Type de carburant                   24776 non-null  object
 5   Puissance fiscale                   24776 non-null  int64
 6   Boite de vitesses                   24776 non-null  object
 7   Nombre de portes                    24776 non-null  int32
 8   Origine                             24776 non-null  object
 9   Premiére main                       24776 non-null  object
 10  état                                24776 non-null  object
 11  Jantes aluminium                    24776 non-null  bool
 12  Airbags                             24776 non-null  bool
 13  Climatisation                       24776 non-null  bool
 14  Systéme de navigation/GPS           24776 non-null  bool
 15  Toit ouvrant                        24776 non-null  bool
 16  Siéges cuir                         24776 non-null  bool
 17  Radar de recul                      24776 non-null  bool
 18  Caméra de recul                     24776 non-null  bool
 19  Vitres électriques                  24776 non-null  bool
 20  ABS                                 24776 non-null  bool
 21  ESP                                 24776 non-null  bool
 22  Régulateur de vitesse               24776 non-null  bool
 23  Limiteur de vitesse                 24776 non-null  bool
 24  CD/MP3/Bluetooth                    24776 non-null  bool
 25  Ordinateur de bord                  24776 non-null  bool
 26  Verrouillage centralisé é distance  24776 non-null  bool
 27  Prix                                24776 non-null  int64
dtypes: bool(16), int32(2), int64(3), object(7)
memory usage: 2.5+ MB

In [30]:
df.isnull().sum()

Marque                                0
Modéle                                0
Année-Modele                          0
Kilométrage                           0
Type de carburant                     0
Puissance fiscale                     0
Boite de vitesses                     0
Nombre de portes                      0
Origine                               0
Premiére main                         0
état                                  0
Jantes aluminium                      0
Airbags                               0
Climatisation                         0
Systéme de navigation/GPS             0
Toit ouvrant                          0
Siéges cuir                           0
Radar de recul                        0
Caméra de recul                       0
Vitres électriques                    0
ABS                                   0
ESP                                   0
Régulateur de vitesse                 0
Limiteur de vitesse                   0
CD/MP3/Bluetooth                      0
Ordinateur de bord                    0
Verrouillage centralisé é distance    0
Prix                                  0
dtype: int64

In [31]:
df['Boite de vitesses'].unique()

array(['manuelle', 'automatique', '--'], dtype=object)

Remplacer les valeurs manquantes dans la colonne 'Boîte de vitesses' par la mode de la colonne

In [33]:
df['Boite de vitesses'] = df['Boite de vitesses'].replace('--', df['Boite de vitesses'].mode()[0])
df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,...,Caméra de recul,Vitres électriques,ABS,ESP,Régulateur de vitesse,Limiteur de vitesse,CD/MP3/Bluetooth,Ordinateur de bord,Verrouillage centralisé é distance,Prix
0,fiat,punto,2007,225000,diesel,5,manuelle,5,ww au maroc,non,...,False,False,True,False,False,False,True,False,False,60000
1,dacia,dokker van,2013,425000,diesel,6,manuelle,3,ww au maroc,non,...,False,False,False,False,False,False,False,False,False,70000
2,dacia,dokker,2014,165000,diesel,6,manuelle,5,ww au maroc,non,...,False,False,False,False,False,False,False,False,False,90000
3,volkswagen,touareg,2005,2500,diesel,10,automatique,5,ww au maroc,oui,...,False,False,False,False,False,False,False,False,False,90000
4,toyota,prado,2007,225000,diesel,12,manuelle,5,ww au maroc,non,...,False,False,True,False,False,False,True,False,False,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,essence,9,manuelle,3,ww au maroc,oui,...,False,False,True,True,False,False,False,False,False,180000
24772,mini,cooper,2007,195000,essence,9,manuelle,3,ww au maroc,non,...,False,False,True,True,False,False,True,False,False,63000
24773,mini,one,2006,12500,essence,8,manuelle,3,ww au maroc,non,...,False,False,True,False,False,False,True,False,False,60000
24774,mini,cooper,2010,145000,essence,9,automatique,3,dedouanee,non,...,False,False,True,True,False,False,True,False,False,85000
24775,mini,cooper,2008,185000,essence,9,manuelle,5,importee neuve,non,...,False,False,False,False,False,False,False,False,False,84000

Extraire le nombre de valeurs uniques par colonne

In [35]:
def get_unique_values_count(data):
    """Retourne un dictionnaire avec le nombre de valeurs uniques par colonne."""
    return {col: data[col].nunique() for col in data.columns}
unique_values_count=get_unique_values_count(df)
unique_values_count

{'Marque': 23,
 'Modéle': 367,
 'Année-Modele': 33,
 'Kilométrage': 36,
 'Type de carburant': 4,
 'Puissance fiscale': 10,
 'Boite de vitesses': 2,
 'Nombre de portes': 2,
 'Origine': 4,
 'Premiére main': 2,
 'état': 6,
 'Jantes aluminium': 1,
 'Airbags': 2,
 'Climatisation': 2,
 'Systéme de navigation/GPS': 1,
 'Toit ouvrant': 1,
 'Siéges cuir': 1,
 'Radar de recul': 1,
 'Caméra de recul': 1,
 'Vitres électriques': 1,
 'ABS': 2,
 'ESP': 2,
 'Régulateur de vitesse': 1,
 'Limiteur de vitesse': 1,
 'CD/MP3/Bluetooth': 2,
 'Ordinateur de bord': 1,
 'Verrouillage centralisé é distance': 1,
 'Prix': 386}

Supprimer les colonnes où il y a une valeur uniques

In [37]:
df.drop(['Jantes aluminium','Systéme de navigation/GPS','Toit ouvrant' ,'Siéges cuir','Radar de recul', 'Caméra de recul', 'Vitres électriques','Régulateur de vitesse', 'Limiteur de vitesse', 'Ordinateur de bord', 'Verrouillage centralisé é distance'],axis=1,inplace=True)
df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,état,Airbags,Climatisation,ABS,ESP,CD/MP3/Bluetooth,Prix
0,fiat,punto,2007,225000,diesel,5,manuelle,5,ww au maroc,non,tres bon,False,True,True,False,True,60000
1,dacia,dokker van,2013,425000,diesel,6,manuelle,3,ww au maroc,non,excellent,False,False,False,False,False,70000
2,dacia,dokker,2014,165000,diesel,6,manuelle,5,ww au maroc,non,tres bon,False,False,False,False,False,90000
3,volkswagen,touareg,2005,2500,diesel,10,automatique,5,ww au maroc,oui,excellent,False,False,False,False,False,90000
4,toyota,prado,2007,225000,diesel,12,manuelle,5,ww au maroc,non,excellent,True,False,True,False,True,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,essence,9,manuelle,3,ww au maroc,oui,excellent,True,True,True,True,False,180000
24772,mini,cooper,2007,195000,essence,9,manuelle,3,ww au maroc,non,tres bon,True,True,True,True,True,63000
24773,mini,one,2006,12500,essence,8,manuelle,3,ww au maroc,non,excellent,True,True,True,False,True,60000
24774,mini,cooper,2010,145000,essence,9,automatique,3,dedouanee,non,tres bon,True,True,True,True,True,85000
24775,mini,cooper,2008,185000,essence,9,manuelle,5,importee neuve,non,tres bon,False,False,False,False,False,84000

Transformer la colonne 'Première main' en booléen

In [39]:
df['Premiére main']=df['Premiére main']=='oui'
df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,état,Airbags,Climatisation,ABS,ESP,CD/MP3/Bluetooth,Prix
0,fiat,punto,2007,225000,diesel,5,manuelle,5,ww au maroc,False,tres bon,False,True,True,False,True,60000
1,dacia,dokker van,2013,425000,diesel,6,manuelle,3,ww au maroc,False,excellent,False,False,False,False,False,70000
2,dacia,dokker,2014,165000,diesel,6,manuelle,5,ww au maroc,False,tres bon,False,False,False,False,False,90000
3,volkswagen,touareg,2005,2500,diesel,10,automatique,5,ww au maroc,True,excellent,False,False,False,False,False,90000
4,toyota,prado,2007,225000,diesel,12,manuelle,5,ww au maroc,False,excellent,True,False,True,False,True,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,essence,9,manuelle,3,ww au maroc,True,excellent,True,True,True,True,False,180000
24772,mini,cooper,2007,195000,essence,9,manuelle,3,ww au maroc,False,tres bon,True,True,True,True,True,63000
24773,mini,one,2006,12500,essence,8,manuelle,3,ww au maroc,False,excellent,True,True,True,False,True,60000
24774,mini,cooper,2010,145000,essence,9,automatique,3,dedouanee,False,tres bon,True,True,True,True,True,85000
24775,mini,cooper,2008,185000,essence,9,manuelle,5,importee neuve,False,tres bon,False,False,False,False,False,84000

Transformer les colonnes contenant des valeurs booléennes en entiers

In [41]:
bool_columns = ['Airbags','Climatisation','ABS','ESP','CD/MP3/Bluetooth','Premiére main']
for c in bool_columns:
    df[c]=df[c].astype(int)

df

,Marque,Modéle,Année-Modele,Kilométrage,Type de carburant,Puissance fiscale,Boite de vitesses,Nombre de portes,Origine,Premiére main,état,Airbags,Climatisation,ABS,ESP,CD/MP3/Bluetooth,Prix
0,fiat,punto,2007,225000,diesel,5,manuelle,5,ww au maroc,0,tres bon,0,1,1,0,1,60000
1,dacia,dokker van,2013,425000,diesel,6,manuelle,3,ww au maroc,0,excellent,0,0,0,0,0,70000
2,dacia,dokker,2014,165000,diesel,6,manuelle,5,ww au maroc,0,tres bon,0,0,0,0,0,90000
3,volkswagen,touareg,2005,2500,diesel,10,automatique,5,ww au maroc,1,excellent,0,0,0,0,0,90000
4,toyota,prado,2007,225000,diesel,12,manuelle,5,ww au maroc,0,excellent,1,0,1,0,1,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,essence,9,manuelle,3,ww au maroc,1,excellent,1,1,1,1,0,180000
24772,mini,cooper,2007,195000,essence,9,manuelle,3,ww au maroc,0,tres bon,1,1,1,1,1,63000
24773,mini,one,2006,12500,essence,8,manuelle,3,ww au maroc,0,excellent,1,1,1,0,1,60000
24774,mini,cooper,2010,145000,essence,9,automatique,3,dedouanee,0,tres bon,1,1,1,1,1,85000
24775,mini,cooper,2008,185000,essence,9,manuelle,5,importee neuve,0,tres bon,0,0,0,0,0,84000

Transformer les titres des colonnes en minuscules, remplacer les espaces par des underscores et enlever les accents

In [43]:
df.columns=df.columns.str.lower().str.strip()
df.columns=df.columns.str.replace(' ','_')
df.columns=df.columns.str.replace('é','e')
df.columns

Index(['marque', 'modele', 'annee-modele', 'kilometrage', 'type_de_carburant',
       'puissance_fiscale', 'boite_de_vitesses', 'nombre_de_portes', 'origine',
       'premiere_main', 'etat', 'airbags', 'climatisation', 'abs', 'esp',
       'cd/mp3/bluetooth', 'prix'],
      dtype='object')

In [44]:
df

,marque,modele,annee-modele,kilometrage,type_de_carburant,puissance_fiscale,boite_de_vitesses,nombre_de_portes,origine,premiere_main,etat,airbags,climatisation,abs,esp,cd/mp3/bluetooth,prix
0,fiat,punto,2007,225000,diesel,5,manuelle,5,ww au maroc,0,tres bon,0,1,1,0,1,60000
1,dacia,dokker van,2013,425000,diesel,6,manuelle,3,ww au maroc,0,excellent,0,0,0,0,0,70000
2,dacia,dokker,2014,165000,diesel,6,manuelle,5,ww au maroc,0,tres bon,0,0,0,0,0,90000
3,volkswagen,touareg,2005,2500,diesel,10,automatique,5,ww au maroc,1,excellent,0,0,0,0,0,90000
4,toyota,prado,2007,225000,diesel,12,manuelle,5,ww au maroc,0,excellent,1,0,1,0,1,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,mini,cabrio,2011,72500,essence,9,manuelle,3,ww au maroc,1,excellent,1,1,1,1,0,180000
24772,mini,cooper,2007,195000,essence,9,manuelle,3,ww au maroc,0,tres bon,1,1,1,1,1,63000
24773,mini,one,2006,12500,essence,8,manuelle,3,ww au maroc,0,excellent,1,1,1,0,1,60000
24774,mini,cooper,2010,145000,essence,9,automatique,3,dedouanee,0,tres bon,1,1,1,1,1,85000
24775,mini,cooper,2008,185000,essence,9,manuelle,5,importee neuve,0,tres bon,0,0,0,0,0,84000

Charger la DataFrame après nettoyage dans un fichier CSV

In [86]:
Q1 = df['prix'].quantile(0.25)
Q3 = df['prix'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df=df[(df['prix'] >= lower_bound) & (df['prix'] <= upper_bound)]

In [88]:
df.to_csv('../../cleaned_data/cars_data_cleaned.csv',index=False)