# Houses Cleaning notebook

In [3]:
import pandas as pd

In [4]:
# Load the uploaded file to inspect its structure
file_path = '../../casablanca_houses_data.csv'
data = pd.read_csv(file_path)
data

,Type,Localisation,Latitude,Longitude,Title,Price,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22 000 DH,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1 230 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2 400 000 DH,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1 550 000 DH,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16 000 000 DH,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1 140 000 DH,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870 000 DH,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495 000 DH,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2 760 000 DH,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [5]:
# Display basic information of the dataset
data_info = data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3300 entries, 0 to 3299
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          3286 non-null   object
 1   Localisation  3300 non-null   object
 2   Latitude      1766 non-null   float64
 3   Longitude     1766 non-null   float64
 4   Title         3300 non-null   object
 5   Price         3134 non-null   object
 6   Tags          3300 non-null   object
dtypes: float64(2), object(5)
memory usage: 180.6+ KB

In [6]:
data.isnull().sum()

Type              14
Localisation       0
Latitude        1534
Longitude       1534
Title              0
Price            166
Tags               0
dtype: int64

In [7]:
data.describe()

          Latitude    Longitude
count  1766.000000  1766.000000
mean     33.561705    -7.630379
std       0.120769     0.042762
min      32.340233    -7.857645
25%      33.559236    -7.648435
50%      33.577979    -7.636442
75%      33.588919    -7.618707
max      33.721772    -7.196045

In [8]:
# Rename the 'Price' column to 'Price in DH' after cleaning
# Clean the 'Price' column
data['Price'] = data['Price'].str.replace('DH', '').str.replace(' ', '').astype(str)
data['Price'] = pd.to_numeric(data['Price'], errors='coerce')

# Rename the column to 'Price in DH'
data.rename(columns={'Price': 'Price in DH'}, inplace=True)
data

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [9]:
data.describe()

          Latitude    Longitude   Price in DH
count  1766.000000  1766.000000  3.132000e+03
mean     33.561705    -7.630379  4.558825e+06
std       0.120769     0.042762  6.796934e+06
min      32.340233    -7.857645  1.600000e+03
25%      33.559236    -7.648435  1.250000e+06
50%      33.577979    -7.636442  2.190750e+06
75%      33.588919    -7.618707  4.800000e+06
max      33.721772    -7.196045  7.140000e+07

In [10]:
# Fill missing numeric values with the mean
numeric_columns = ['Price in DH', 'Latitude', 'Longitude']
for col in numeric_columns:
    if col in data.columns:
        data[col].fillna(data[col].mean(), inplace=True)

data

/tmp/ipykernel_12558/2756811728.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [11]:
# Fill missing non-numeric values with the mode
non_numeric_columns = ['Type']
for col in non_numeric_columns:
    if col in data.columns:
        data[col].fillna(data[col].mode()[0], inplace=True)

data

/tmp/ipykernel_12558/3912347108.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mode()[0], inplace=True)

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [12]:
data.isnull().sum()

Type            0
Localisation    0
Latitude        0
Longitude       0
Title           0
Price in DH     0
Tags            0
dtype: int64

In [13]:
# Display unique values in the 'Type' column
unique_types = data['Type'].unique()
unique_types

array(['Appartements Casablanca', 'Villas & maisons de luxe Casablanca',
       'Riad Casablanca', 'Maisons Casablanca'], dtype=object)

In [14]:
# Display unique values in the 'Localisation' column
unique_localisations = data['Localisation'].unique()
print(unique_localisations)

['Casablanca Finance City à Casablanca' 'Anfa à Casablanca'
 'La Gironde à Casablanca' 'Bourgogne Ouest à Casablanca'
 'Les princesses à Casablanca' "Triangle d'Or à Casablanca"
 'Maârif Extension à Casablanca' 'Anassi à Casablanca'
 'Californie à Casablanca' 'Maârif à Casablanca' 'Racine à Casablanca'
 'Gauthier à Casablanca' 'Val Fleury à Casablanca'
 'Beauséjour à Casablanca' 'Riviera à Casablanca'
 'Sidi Maarouf à Casablanca' 'Ain Diab à Casablanca'
 'Racine Extension à Casablanca' 'Palmier à Casablanca'
 'El Manar - El Hank à Casablanca' 'Oasis à Casablanca'
 'Hay Lmkansa à Casablanca' 'CIL (Hay Salam) à Casablanca'
 'Les Crêtes à Casablanca' 'Les Hôpitaux à Casablanca'
 'Bourgogne Est à Casablanca' 'Ain Diab Extension à Casablanca'
 'Hay Alamal à Casablanca' 'Mers Sultan à Casablanca'
 'Laymoune à Casablanca' 'Longchamps (Hay Al Hanâa) à Casablanca'
 'Oulfa à Casablanca' 'Belvédère à Casablanca' 'Centre Ville à Casablanca'
 'Derb Ghalef à Casablanca' 'Aïn Sebaâ à Casablanca'
 'Hay Alhoda à Casablanca' 'Polo à Casablanca' 'Hay Zobir à Casablanca'
 'Casablanca' 'Foncière à Casablanca' 'Anfa Supérieur à Casablanca'
 'Ain Borja à Casablanca' 'Hermitage à Casablanca' 'Benjdia à Casablanca'
 'Ain Chock à Casablanca' 'Burger à Casablanca'
 'Plateau (Al Batha) à Casablanca'
 'Ferme Bretonne (Hay Arraha) à Casablanca'
 'Casablanca Marina à Casablanca' 'Al Hadika à Casablanca'
 'Port à Casablanca' 'Hay Moulay Rachid 1 à Casablanca'
 'Lissasfa à Casablanca' 'Al Azhar à Casablanca' 'Mandarona à Casablanca'
 'Nassim 1 à Casablanca' 'Tantonville à Casablanca'
 'Sidi Belyout à Casablanca' 'Bernoussi à Casablanca'
 'Ahl Loghlam (Hay Assalam) à Casablanca' 'Franceville à Casablanca'
 'Salmia 2 à Casablanca' 'Itissal à Casablanca'
 'Moulay Youssef à Casablanca' 'Derb Chorfa à Casablanca'
 'Derb Loubila à Casablanca' 'Sidi Moumen à Casablanca'
 'Hay Almassira 2 à Casablanca' 'Nassim 2 à Casablanca'
 'Hay Hassani à Casablanca' 'Derb Abdellah à Casablanca'
 'Roches Noires à Casablanca' 'Hay Al Qods à Casablanca'
 'Al Qods à Casablanca' 'Hay Arrahma à Casablanca'
 'Garage Allal à Casablanca' 'Sidi Othmane à Casablanca'
 'Hay Al Amal à Casablanca' 'Michouar à Casablanca'
 'Hay Inara à Casablanca' 'Hay Mansour à Casablanca'
 'Beausite à Casablanca' 'La Vilette à Casablanca'
 'Derb Moulay Cherif à Casablanca' 'Quartier Bachkou à Casablanca'
 'Hay Lalla Meriem à Casablanca' 'Hay Tasahol à Casablanca'
 "Hay M'barka à Casablanca" 'La Floride à Casablanca'
 'Hay Chrifa à Casablanca' 'Sidi El Khadir à Casablanca'
 'Hay Hakam à Casablanca' 'Derb Salama à Casablanca'
 'Derb Omar à Casablanca' 'Hay Moulay Abdellah à Casablanca'
 'Hay Mohammadi à Casablanca' 'Habbous à Casablanca'
 'Al Osra à Casablanca' 'Tacharouk (Hay Al Walaa) à Casablanca'
 'Hay Tarik à Casablanca' 'Zone Industrielle Moulay Rachid à Casablanca'
 'Al Madina Aljadida à Casablanca' 'Quartier Cheminots à Casablanca'
 'Hay Albaraka à Casablanca' 'Hay Salama à Casablanca'
 'Hay Adil à Casablanca' 'Hay Arsalan à Casablanca'
 'Al Hassania à Casablanca']

In [15]:
data["Tags"][10]

"['144 m²', '5 Pièces', '3 Chambres', '3 Salles de bains', 'Bon état']"

In [16]:
from collections import Counter

# Check the length of each list in the 'Tags' column
# Assuming 'Tags' is already a list or list-like string that can be evaluated
data['Tags_length'] = data['Tags'].apply(lambda x: len(eval(x)) if isinstance(x, str) and x.startswith('[') else 0)

# Count the unique occurrences of list lengths
tags_length_counts = Counter(data['Tags_length'])

tags_length_counts

Counter({7: 1178, 6: 1117, 5: 693, 4: 180, 3: 120, 1: 10, 2: 2})

In [17]:
# Create a copy of the dataset to preserve the original
data_separated = data.copy()

# Parse the 'Tags' column into lists
data_separated['Tags_list'] = data_separated['Tags'].apply(lambda x: eval(x) if isinstance(x, str) and x.startswith('[') else [])

# Find the maximum number of elements in the lists
max_length = 7

# Separate the elements into individual columns
for i in range(max_length):
    data_separated[f'Tag_{i+1}'] = data_separated['Tags_list'].apply(lambda x: x[i] if i < len(x) else "empty")

# Drop the 'Tags_list' column if no longer needed
data_separated.drop(columns=['Tags_list'], inplace=True)

# Save or preview the separated dataset
# data_separated.to_csv('separated_tags_dataset.csv', index=False)  # Save cleaned data if needed
data_separated  # Display the first few rows

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags,Tags_length,Tag_1,Tag_2,Tag_3,Tag_4,Tag_5,Tag_6,Tag_7
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles...",7,219 m²,4 Pièces,3 Chambres,3 Salles de bains,Nouveau,Moins d'un an,11ème étage
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ...",7,86 m²,3 Pièces,2 Chambres,2 Salles de bains,Bon état,10-20 ans,1er étage
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d...",7,86 m²,3 Pièces,2 Chambres,1 Salle de bain,Bon état,10-20 ans,5ème étage
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles...",7,180 m²,5 Pièces,3 Chambres,3 Salles de bains,Bon état,10-20 ans,3ème étage
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles...",7,120 m²,5 Pièces,3 Chambres,2 Salles de bains,Bon état,5-10 ans,5ème étage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle...",5,1040 m²,8 Pièces,5 Chambres,6 Salles de bains,Bon état,empty,empty
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ...",6,74 m²,3 Pièces,2 Chambres,2 Salles de bains,Bon état,4ème étage,empty
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d...",7,56 m²,2 Pièces,1 Chambre,2 Salles de bains,Nouveau,Moins d'un an,4ème étage
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d...",7,68 m²,3 Pièces,2 Chambres,1 Salle de bain,Bon état,5-10 ans,4ème étage
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles...",7,230 m²,9 Pièces,3 Chambres,3 Salles de bains,Bon état,10-20 ans,6ème étage

In [18]:
# Function to ensure 'm²' is in Tag_1 or add '0m²' if missing
def ensure_m2_in_tag1(row, max_tags=7):
    tags = [row[f'Tag_{i+1}'] for i in range(max_tags) if row[f'Tag_{i+1}'] != "empty"]

    # Check if any tag contains "m²"
    m2_tags = [tag for tag in tags if "m²" in tag]

    if m2_tags:
        # If "m²" exists, ensure it's in Tag_1
        m2_value = m2_tags[0]  # Take the first occurrence
        tags.remove(m2_value)  # Remove it from its original position
        tags.insert(0, m2_value)  # Place it in the first position
    else:
        # If no "m²" exists, add "0m²" to Tag_1
        tags.insert(0, "0m²")
        row['Tags_length'] += 1

    # Update the tags back into the row
    for i in range(max_tags):
        row[f'Tag_{i+1}'] = tags[i] if i < len(tags) else "empty"

    return row

# Apply the transformation to ensure "m²" is in Tag_1
data_separated = data_separated.apply(ensure_m2_in_tag1, axis=1)

# Check the first few rows for validation
data_separated[['Tag_1', 'Tag_2', 'Tag_3', 'Tag_4', 'Tags_length']].head()

    Tag_1     Tag_2       Tag_3              Tag_4  Tags_length
0  219 m²  4 Pièces  3 Chambres  3 Salles de bains            7
1   86 m²  3 Pièces  2 Chambres  2 Salles de bains            7
2   86 m²  3 Pièces  2 Chambres    1 Salle de bain            7
3  180 m²  5 Pièces  3 Chambres  3 Salles de bains            7
4  120 m²  5 Pièces  3 Chambres  2 Salles de bains            7

In [19]:
data_separated[['Tag_1', 'Tag_2', 'Tag_3', 'Tag_4', 'Tag_5', 'Tag_6', 'Tag_7', 'Tags_length']]

,Tag_1,Tag_2,Tag_3,Tag_4,Tag_5,Tag_6,Tag_7,Tags_length
0,219 m²,4 Pièces,3 Chambres,3 Salles de bains,Nouveau,Moins d'un an,11ème étage,7
1,86 m²,3 Pièces,2 Chambres,2 Salles de bains,Bon état,10-20 ans,1er étage,7
2,86 m²,3 Pièces,2 Chambres,1 Salle de bain,Bon état,10-20 ans,5ème étage,7
3,180 m²,5 Pièces,3 Chambres,3 Salles de bains,Bon état,10-20 ans,3ème étage,7
4,120 m²,5 Pièces,3 Chambres,2 Salles de bains,Bon état,5-10 ans,5ème étage,7
...,...,...,...,...,...,...,...,...
3295,1040 m²,8 Pièces,5 Chambres,6 Salles de bains,Bon état,empty,empty,5
3296,74 m²,3 Pièces,2 Chambres,2 Salles de bains,Bon état,4ème étage,empty,6
3297,56 m²,2 Pièces,1 Chambre,2 Salles de bains,Nouveau,Moins d'un an,4ème étage,7
3298,68 m²,3 Pièces,2 Chambres,1 Salle de bain,Bon état,5-10 ans,4ème étage,7
3299,230 m²,9 Pièces,3 Chambres,3 Salles de bains,Bon état,10-20 ans,6ème étage,7

In [20]:
# Function to ensure 'Pièces' is in Tag_2 or add '0 Pièces' if missing
def ensure_pieces_in_tag2(row, max_tags=7):
    tags = [row[f'Tag_{i+1}'] for i in range(max_tags) if row[f'Tag_{i+1}'] != "empty"]

    # Check if any tag contains "Pièces"
    pieces_tags = [tag for tag in tags if "Pièces" in tag]

    if pieces_tags:
        # If "Pièces" exists, ensure it's in Tag_2
        pieces_value = pieces_tags[0]  # Take the first occurrence
        tags.remove(pieces_value)  # Remove it from its original position
        if len(tags) > 1:
            tags.insert(1, pieces_value)  # Place it in the second position
    else:
        # If no "Pièces" exists, add "0 Pièces" to Tag_2
        tags.insert(1, "0 Pièces")
        row['Tags_length'] += 1

    # Update the tags back into the row
    for i in range(max_tags):
        row[f'Tag_{i+1}'] = tags[i] if i < len(tags) else "empty"

    return row

# Apply the transformation to ensure "Pièces" is in Tag_2
data_separated = data_separated.apply(ensure_pieces_in_tag2, axis=1)

# Check the first few rows for validation
data_separated[['Tag_2', 'Tags_length']]

         Tag_2  Tags_length
0     4 Pièces            7
1     3 Pièces            7
2     3 Pièces            7
3     5 Pièces            7
4     5 Pièces            7
...        ...          ...
3295  8 Pièces            5
3296  3 Pièces            6
3297  2 Pièces            7
3298  3 Pièces            7
3299  9 Pièces            7

[3300 rows x 2 columns]

In [21]:
# Function to ensure 'Chambres' or 'Chambre' is in Tag_3 or add '0 Chambres' if missing
def ensure_chambres_in_tag3(row, max_tags=7):
    tags = [row[f'Tag_{i+1}'] for i in range(max_tags) if row[f'Tag_{i+1}'] != "empty"]

    # Check if any tag contains "Chambres" or "Chambre"
    chambres_tags = [tag for tag in tags if "Chambres" in tag or "Chambre" in tag]

    if chambres_tags:
        # If "Chambres" or "Chambre" exists, ensure it's in Tag_3
        chambres_value = chambres_tags[0]  # Take the first occurrence
        tags.remove(chambres_value)  # Remove it from its original position
        if len(tags) > 2:
            tags.insert(2, chambres_value)  # Place it in the third position
    else:
        # If no "Chambres" or "Chambre" exists, add "0 Chambres" to Tag_3
        tags.insert(2, "0 Chambres")
        row['Tags_length'] += 1

    # Update the tags back into the row
    for i in range(max_tags):
        row[f'Tag_{i+1}'] = tags[i] if i < len(tags) else "empty"

    return row

# Apply the transformation to ensure "Chambres" is in Tag_3
data_separated = data_separated.apply(ensure_chambres_in_tag3, axis=1)

# Check the first few rows for validation
data_separated[['Tag_3', 'Tags_length']]

           Tag_3  Tags_length
0     3 Chambres            7
1     2 Chambres            7
2     2 Chambres            7
3     3 Chambres            7
4     3 Chambres            7
...          ...          ...
3295  5 Chambres            5
3296  2 Chambres            6
3297   1 Chambre            7
3298  2 Chambres            7
3299  3 Chambres            7

[3300 rows x 2 columns]

In [22]:
# Function to ensure 'Salles de bains' or 'Salle de bain' is in Tag_4 or add '0 Salles de bains' if missing
def ensure_salles_in_tag4(row, max_tags=7):
    tags = [row[f'Tag_{i+1}'] for i in range(max_tags) if row[f'Tag_{i+1}'] != "empty"]

    # Check if any tag contains "Salles de bains" or "Salle de bain"
    salles_tags = [tag for tag in tags if "Salles de bains" in tag or "Salle de bain" in tag]

    if salles_tags:
        # If "Salles de bains" or "Salle de bain" exists, ensure it's in Tag_4
        salles_value = salles_tags[0]  # Take the first occurrence
        tags.remove(salles_value)  # Remove it from its original position
        if len(tags) > 3:
            tags.insert(3, salles_value)  # Place it in the fourth position
    else:
        # If no "Salles de bains" or "Salle de bain" exists, add "0 Salles de bains" to Tag_4
        tags.insert(3, "0 Salles de bains")
        row['Tags_length'] += 1

    # Update the tags back into the row
    for i in range(max_tags):
        row[f'Tag_{i+1}'] = tags[i] if i < len(tags) else "empty"

    return row

# Apply the transformation to ensure "Salles de bains" is in Tag_4
data_separated = data_separated.apply(ensure_salles_in_tag4, axis=1)

# Check the first few rows for validation
data_separated[['Tag_4', 'Tags_length']]

                  Tag_4  Tags_length
0     3 Salles de bains            7
1     2 Salles de bains            7
2       1 Salle de bain            7
3     3 Salles de bains            7
4     2 Salles de bains            7
...                 ...          ...
3295  6 Salles de bains            5
3296  2 Salles de bains            6
3297  2 Salles de bains            7
3298    1 Salle de bain            7
3299  3 Salles de bains            7

[3300 rows x 2 columns]

In [23]:
data_separated['Tag_5'].unique()

array(['Nouveau', 'Bon état', 'À rénover', 'empty', '4ème étage',
       '1 Pièce', '5ème étage', '3ème étage', '2ème étage', '1er étage',
       '7ème étage', '9ème étage'], dtype=object)

In [24]:
def fix_tags_5_6_7(row, max_tags=7):
    tags = [row[f'Tag_{i+1}'] for i in range(max_tags) if row[f'Tag_{i+1}'] != "empty"]

    # Extract values for each tag based on the categories
    tag_5_condition = next((tag for tag in tags if tag in ["Nouveau", "Bon état", "À rénover"]), "Indéterminé")
    tag_6_duration = next((tag for tag in tags if "Moins d'un an" in tag or "ans" in tag), "Indéterminée")
    tag_7_floor = next((tag for tag in tags if "étage" in tag), "empty")

    # Remove the extracted values from their original positions
    tags = [tag for tag in tags if tag not in [tag_5_condition, tag_6_duration, tag_7_floor]]

    # Update the tags in the correct positions
    tags.insert(4, tag_5_condition)  # Tag_5
    tags.insert(5, tag_6_duration)   # Tag_6
    tags.insert(6, tag_7_floor)     # Tag_7

    # Update the row with the cleaned tags
    for i in range(max_tags):
        row[f'Tag_{i+1}'] = tags[i] if i < len(tags) else "empty"

    return row

# Apply the transformation to the dataset
data_separated = data_separated.apply(fix_tags_5_6_7, axis=1)

# Check the updated tags
data_separated[['Tag_5', 'Tag_6', 'Tag_7', 'Tags_length']].head()

      Tag_5          Tag_6        Tag_7  Tags_length
0   Nouveau  Moins d'un an  11ème étage            7
1  Bon état      10-20 ans    1er étage            7
2  Bon état      10-20 ans   5ème étage            7
3  Bon état      10-20 ans   3ème étage            7
4  Bon état       5-10 ans   5ème étage            7

In [25]:
data_separated.isnull().sum()

Type            0
Localisation    0
Latitude        0
Longitude       0
Title           0
Price in DH     0
Tags            0
Tags_length     0
Tag_1           0
Tag_2           0
Tag_3           0
Tag_4           0
Tag_5           0
Tag_6           0
Tag_7           0
dtype: int64

In [26]:
data_separated["Tag_3"].unique()

array(['3 Chambres', '2 Chambres', '5 Chambres', '1 Chambre',
       '4 Chambres', '6 Chambres', '7 Chambres', '0 Chambres',
       '15 Chambres', '0 Salles de bains', '10 Chambres', '18 Chambres',
       '11 Chambres', '8 Chambres', '9 Chambres'], dtype=object)

In [27]:
# Replace '0 Salles de bains' in Tag_3 with 'empty'
data_separated['Tag_3'] = data_separated['Tag_3'].replace('0 Salles de bains', 'empty')

# Check the updated Tag_3 column for validation
data_separated['Tag_3'].value_counts()

Tag_3
3 Chambres     1183
2 Chambres      933
4 Chambres      549
1 Chambre       323
5 Chambres      173
6 Chambres       61
empty            32
7 Chambres       19
0 Chambres       10
15 Chambres       4
10 Chambres       4
18 Chambres       4
11 Chambres       2
8 Chambres        2
9 Chambres        1
Name: count, dtype: int64

In [28]:
data_separated["Tag_6"].unique()

array(["Moins d'un an", '10-20 ans', '5-10 ans', '20-30 ans',
       'Indéterminée', '1-5 ans', '30-50 ans', 'empty', '50-70 ans'],
      dtype=object)

In [29]:
def move_rez_to_tag7_with_condition(row):
    if row['Tag_6'] == 'Rez-de-chaussée':
        # Check if Tag_7 is empty or "Indéterminée"
        if row['Tag_7'] in ['empty', 'Indéterminée']:
            row['Tag_7'] = 'Rez-de-chaussée'  # Move "Rez-de-chaussée" to Tag_7
        row['Tag_6'] = 'empty'  # Replace Tag_6 with "empty"
    return row

# Apply the transformation to the dataset
data_separated = data_separated.apply(move_rez_to_tag7_with_condition, axis=1)

# Check the updated columns
data_separated[['Tag_6', 'Tag_7']].head()

           Tag_6        Tag_7
0  Moins d'un an  11ème étage
1      10-20 ans    1er étage
2      10-20 ans   5ème étage
3      10-20 ans   3ème étage
4       5-10 ans   5ème étage

In [30]:
data_separated[["Tag_1", "Tag_2", "Tag_3", "Tag_4", "Tag_5", "Tag_6", "Tag_7",]]

,Tag_1,Tag_2,Tag_3,Tag_4,Tag_5,Tag_6,Tag_7
0,219 m²,4 Pièces,3 Chambres,3 Salles de bains,Nouveau,Moins d'un an,11ème étage
1,86 m²,3 Pièces,2 Chambres,2 Salles de bains,Bon état,10-20 ans,1er étage
2,86 m²,3 Pièces,2 Chambres,1 Salle de bain,Bon état,10-20 ans,5ème étage
3,180 m²,5 Pièces,3 Chambres,3 Salles de bains,Bon état,10-20 ans,3ème étage
4,120 m²,5 Pièces,3 Chambres,2 Salles de bains,Bon état,5-10 ans,5ème étage
...,...,...,...,...,...,...,...
3295,1040 m²,8 Pièces,5 Chambres,6 Salles de bains,Bon état,Indéterminée,empty
3296,74 m²,3 Pièces,2 Chambres,2 Salles de bains,Bon état,Indéterminée,4ème étage
3297,56 m²,2 Pièces,1 Chambre,2 Salles de bains,Nouveau,Moins d'un an,4ème étage
3298,68 m²,3 Pièces,2 Chambres,1 Salle de bain,Bon état,5-10 ans,4ème étage
3299,230 m²,9 Pièces,3 Chambres,3 Salles de bains,Bon état,10-20 ans,6ème étage

In [31]:
data_separated["Tag_7"].unique()

array(['11ème étage', '1er étage', '5ème étage', '3ème étage', 'empty',
       '4ème étage', '6ème étage', '10ème étage', '2ème étage',
       '7ème étage', '9ème étage', '12ème étage', '8ème étage',
       '20ème étage', '15ème étage'], dtype=object)

In [32]:
# Rename the column
data_separated.rename(columns={'Tag_1': 'Area in m²'}, inplace=True)

# Extract only the numeric part of the data
data_separated['Area in m²'] = data_separated['Area in m²'].str.extract(r'(\d+)').astype(float)

# Check the updated column
data_separated[['Area in m²']].head()

   Area in m²
0       219.0
1        86.0
2        86.0
3       180.0
4       120.0

In [34]:
# Rename the column
data_separated.rename(columns={'Tag_2': 'Rooms'}, inplace=True)

# Extract numeric values from the column, handling "empty" and "0 Pièces"
data_separated['Rooms'] = data_separated['Rooms'].replace(
    ['empty', '0 Pièces'], None
).str.extract(r'(\d+)').astype(float)

# Calculate the mean of the non-missing values
mean_rooms = data_separated['Rooms'].mean()

# Replace missing values with the mean
data_separated['Rooms'].fillna(mean_rooms, inplace=True)

# Check the updated column
data_separated[['Rooms']].head()

/tmp/ipykernel_12558/2399376301.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_separated['Rooms'].fillna(mean_rooms, inplace=True)

   Rooms
0    4.0
1    3.0
2    3.0
3    5.0
4    5.0

In [36]:
# Rename the column
data_separated.rename(columns={'Tag_3': 'Bedrooms'}, inplace=True)

# Extract numeric values from the column, handling "empty" and "0 Pièces"
data_separated['Bedrooms'] = data_separated['Bedrooms'].replace(
    ['empty', '0 Chambres'], None
).str.extract(r'(\d+)').astype(float)

# Calculate the mean of the non-missing values
mean_rooms = data_separated['Bedrooms'].mean()

# Replace missing values with the mean
data_separated['Bedrooms'].fillna(mean_rooms, inplace=True)

# Check the updated column
data_separated[['Bedrooms']].head()

/tmp/ipykernel_12558/4170650068.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_separated['Bedrooms'].fillna(mean_rooms, inplace=True)

   Bedrooms
0       3.0
1       2.0
2       2.0
3       3.0
4       3.0

In [38]:
# Rename the column
data_separated.rename(columns={'Tag_4': 'Bathrooms'}, inplace=True)

# Extract numeric values from the column, handling "empty" and "0 Pièces"
data_separated['Bathrooms'] = data_separated['Bathrooms'].replace(
    ['Indéterminé', '0 Salles de bains'], None
).str.extract(r'(\d+)').astype(float)

# Calculate the mean of the non-missing values
mean_rooms = data_separated['Bathrooms'].mean()

# Replace missing values with the mean
data_separated['Bathrooms'].fillna(mean_rooms, inplace=True)

# Check the updated column
data_separated[['Bathrooms']].head()

/tmp/ipykernel_12558/500529700.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_separated['Bathrooms'].fillna(mean_rooms, inplace=True)

   Bathrooms
0        3.0
1        2.0
2        1.0
3        3.0
4        2.0

In [40]:
# Rename the column
data_separated.rename(columns={'Tag_5': 'Condition'}, inplace=True)

# Replace "Indéterminé" and "Indéterminée" with NaN (to handle missing values)
data_separated['Condition'] = data_separated['Condition'].replace(
    ['Indéterminé', 'Indéterminée'], None
)

# Calculate the mode of the column
mode_condition = data_separated['Condition'].mode()[0]

# Replace missing values with the mode
data_separated['Condition'].fillna(mode_condition, inplace=True)

# Check the updated column
data_separated[['Condition']].head()

/tmp/ipykernel_12558/2385856508.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_separated['Condition'].fillna(mode_condition, inplace=True)

  Condition
0   Nouveau
1  Bon état
2  Bon état
3  Bon état
4  Bon état

In [42]:
# Rename the column
data_separated.rename(columns={'Tag_6': 'House Age'}, inplace=True)

# Replace "Indéterminée" and "empty" with NaN
data_separated['House Age'] = data_separated['House Age'].replace(
    ['Indéterminée', 'empty'], None
)

# Calculate the mode of the column
mode_house_age = data_separated['House Age'].mode()[0]

# Replace missing values with the mode
data_separated['House Age'].fillna(mode_house_age, inplace=True)

# Check the updated column
data_separated[['House Age']].head()

/tmp/ipykernel_12558/4288309194.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_separated['House Age'].fillna(mode_house_age, inplace=True)

       House Age
0  Moins d'un an
1      10-20 ans
2      10-20 ans
3      10-20 ans
4       5-10 ans

In [44]:
# Rename the column
data_separated.rename(columns={'Tag_7': 'Floor'}, inplace=True)

# Replace "empty" with NaN
data_separated['Floor'] = data_separated['Floor'].replace('empty', None)

# Calculate the mode of the column
mode_floor = data_separated['Floor'].mode()[0]

# Replace missing values with the mode
data_separated['Floor'].fillna(mode_floor, inplace=True)

# Check the updated column
data_separated[['Floor']].head()

/tmp/ipykernel_12558/976359716.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_separated['Floor'].fillna(mode_floor, inplace=True)

         Floor
0  11ème étage
1    1er étage
2   5ème étage
3   3ème étage
4   5ème étage

In [46]:
# Extract numeric values from the column, handling "empty" and "0 Pièces"
data_separated['Floor'] = data_separated['Floor'].replace(
    ['Indéterminé', '0 Salles de bains'], None
).str.extract(r'(\d+)').astype(float)

# Check the updated column
data_separated[['Floor']].head()

   Floor
0   11.0
1    1.0
2    5.0
3    3.0
4    5.0

In [48]:
data_separated

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags,Tags_length,Area in m²,Rooms,Bedrooms,Bathrooms,Condition,House Age,Floor
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles...",7,219.0,4.0,3.0,3.0,Nouveau,Moins d'un an,11.0
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ...",7,86.0,3.0,2.0,2.0,Bon état,10-20 ans,1.0
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d...",7,86.0,3.0,2.0,1.0,Bon état,10-20 ans,5.0
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles...",7,180.0,5.0,3.0,3.0,Bon état,10-20 ans,3.0
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles...",7,120.0,5.0,3.0,2.0,Bon état,5-10 ans,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle...",5,1040.0,8.0,5.0,6.0,Bon état,10-20 ans,3.0
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ...",6,74.0,3.0,2.0,2.0,Bon état,10-20 ans,4.0
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d...",7,56.0,2.0,1.0,2.0,Nouveau,Moins d'un an,4.0
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d...",7,68.0,3.0,2.0,1.0,Bon état,5-10 ans,4.0
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles...",7,230.0,9.0,3.0,3.0,Bon état,10-20 ans,6.0

In [55]:
# Function to process the 'House Age' column
def process_house_age(age):
    if "Moins d'un an" in age:
        return 0  # Special case for "Moins d'un an"
    else:
        # Extract the numerical part and calculate the midpoint
        numbers = [int(x) for x in age.replace(" ans", "").split('-')]
        return sum(numbers) // 2  # Midpoint of the interval

# Apply the transformation
data_separated['House Age in ans'] = data_separated['House Age'].apply(process_house_age)

# Drop the original column
data_separated.drop('House Age', axis=1, inplace=True)

# Display the result
print(data_separated)

                                     Type  \
0                 Appartements Casablanca
1                 Appartements Casablanca
2                 Appartements Casablanca
3                 Appartements Casablanca
4                 Appartements Casablanca
...                                   ...
3295  Villas & maisons de luxe Casablanca
3296              Appartements Casablanca
3297              Appartements Casablanca
3298              Appartements Casablanca
3299              Appartements Casablanca

                              Localisation   Latitude  Longitude  \
0     Casablanca Finance City à Casablanca  33.561705  -7.630379
1                        Anfa à Casablanca  33.561705  -7.630379
2                  La Gironde à Casablanca  33.561705  -7.630379
3             Bourgogne Ouest à Casablanca  33.561705  -7.630379
4              Les princesses à Casablanca  33.574209  -7.644182
...                                    ...        ...        ...
3295               Californie à Casablanca  33.535958  -7.625628
3296               Val Fleury à Casablanca  33.574082  -7.639103
3297                Hermitage à Casablanca  33.568940  -7.615812
3298              Hay Arrahma à Casablanca  33.598785  -7.567606
3299             Les Hôpitaux à Casablanca  33.577979  -7.620006

                                                  Title  Price in DH  \
0         Somptueux appartement à louer au tour végétal      22000.0
1        A vendre appartement 86m face ELBILIA lahjajma    1230000.0
2           A vendre bel appartement 2 chambres Gironde     900000.0
3      A vendre appartement 180m clinique Badr pas cher    2400000.0
4     Appartement 3 chambres yaacoub almansour pas cher    1550000.0
...                                                 ...          ...
3295              Superbe villa à vendre sur Californie   16000000.0
3296  2 chambres séjour au 4ème étage orienté est ouest    1140000.0
3297     Magnifique studio de 56m2 sur Boulevard Anoual     870000.0
3298      Bel appartement à vendre à résidence Almanzeh     495000.0
3299        Grand et lumineux appartement à Abdelmoumen    2760000.0

                                                   Tags  Tags_length  \
0     ['219 m²', '4 Pièces', '3 Chambres', '3 Salles...            7
1     ['86 m²', '3 Pièces', '2 Chambres', '2 Salles ...            7
2     ['86 m²', '3 Pièces', '2 Chambres', '1 Salle d...            7
3     ['180 m²', '5 Pièces', '3 Chambres', '3 Salles...            7
4     ['120 m²', '5 Pièces', '3 Chambres', '2 Salles...            7
...                                                 ...          ...
3295  ['1040 m²', '8 Pièces', '5 Chambres', '6 Salle...            5
3296  ['74 m²', '3 Pièces', '2 Chambres', '2 Salles ...            6
3297  ['56 m²', '2 Pièces', '1 Chambre', '2 Salles d...            7
3298  ['68 m²', '3 Pièces', '2 Chambres', '1 Salle d...            7
3299  ['230 m²', '9 Pièces', '3 Chambres', '3 Salles...            7

      Area in m²  Rooms  Bedrooms  Bathrooms Condition  Floor  \
0          219.0    4.0       3.0        3.0   Nouveau   11.0
1           86.0    3.0       2.0        2.0  Bon état    1.0
2           86.0    3.0       2.0        1.0  Bon état    5.0
3          180.0    5.0       3.0        3.0  Bon état    3.0
4          120.0    5.0       3.0        2.0  Bon état    5.0
...          ...    ...       ...        ...       ...    ...
3295      1040.0    8.0       5.0        6.0  Bon état    3.0
3296        74.0    3.0       2.0        2.0  Bon état    4.0
3297        56.0    2.0       1.0        2.0   Nouveau    4.0
3298        68.0    3.0       2.0        1.0  Bon état    4.0
3299       230.0    9.0       3.0        3.0  Bon état    6.0

      House Age in ans
0                    0
1                   15
2                   15
3                   15
4                    7
...                ...
3295                15
3296                15
3297                 0
3298                 7
3299                15

[3300 rows x 15 columns]

In [57]:
data_separated

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags,Tags_length,Area in m²,Rooms,Bedrooms,Bathrooms,Condition,Floor,House Age in ans
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles...",7,219.0,4.0,3.0,3.0,Nouveau,11.0,0
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ...",7,86.0,3.0,2.0,2.0,Bon état,1.0,15
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d...",7,86.0,3.0,2.0,1.0,Bon état,5.0,15
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles...",7,180.0,5.0,3.0,3.0,Bon état,3.0,15
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles...",7,120.0,5.0,3.0,2.0,Bon état,5.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle...",5,1040.0,8.0,5.0,6.0,Bon état,3.0,15
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ...",6,74.0,3.0,2.0,2.0,Bon état,4.0,15
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d...",7,56.0,2.0,1.0,2.0,Nouveau,4.0,0
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d...",7,68.0,3.0,2.0,1.0,Bon état,4.0,7
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles...",7,230.0,9.0,3.0,3.0,Bon état,6.0,15

In [50]:
data_separated.isnull().sum()

Type            0
Localisation    0
Latitude        0
Longitude       0
Title           0
Price in DH     0
Tags            0
Tags_length     0
Area in m²      0
Rooms           0
Bedrooms        0
Bathrooms       0
Condition       0
House Age       0
Floor           0
dtype: int64

In [59]:
# Save to a CSV file
data_separated.to_csv('Cleaned_dataset.csv', index=False)  # `index=False` avoids saving the index column
print("Dataset saved to 'dataset.csv'")

Dataset saved to 'dataset.csv'

In [67]:
# Save to a CSV file
data_separated.to_json('Cleaned_dataset.json', orient='records', lines=True)  # `index=False` avoids saving the index column
print("Dataset saved to 'dataset.json'")

Dataset saved to 'dataset.json'