# Houses Cleaning notebook

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load the uploaded file to inspect its structure
file_path = '../../casablanca_houses_data.csv'
df = pd.read_csv(file_path)
df

,Type,Localisation,Latitude,Longitude,Title,Price,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22 000 DH,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1 230 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2 400 000 DH,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1 550 000 DH,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16 000 000 DH,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1 140 000 DH,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870 000 DH,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495 000 DH,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2 760 000 DH,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [4]:
df.isnull().sum()

Type              14
Localisation       0
Latitude        1534
Longitude       1534
Title              0
Price            166
Tags               0
dtype: int64

In [5]:
#clean type column to keep only the first word
df['Type'] = df['Type'].apply(lambda x: str(x).split(' ')[0])
df

,Type,Localisation,Latitude,Longitude,Title,Price,Tags
0,Appartements,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22 000 DH,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1 230 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2 400 000 DH,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1 550 000 DH,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16 000 000 DH,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1 140 000 DH,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870 000 DH,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495 000 DH,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2 760 000 DH,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [6]:
#remove rows with missing price and clean price (remove DH and change type)
# Clean the 'Price' column
df['Price'] = df['Price'].str.replace('DH', '').str.replace(' ', '').astype(str)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Rename the column to 'Price in DH'
df.rename(columns={'Price': 'Price in DH'}, inplace=True)
df

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [7]:
df.describe()

          Latitude    Longitude   Price in DH
count  1766.000000  1766.000000  3.132000e+03
mean     33.561705    -7.630379  4.558825e+06
std       0.120769     0.042762  6.796934e+06
min      32.340233    -7.857645  1.600000e+03
25%      33.559236    -7.648435  1.250000e+06
50%      33.577979    -7.636442  2.190750e+06
75%      33.588919    -7.618707  4.800000e+06
max      33.721772    -7.196045  7.140000e+07

In [8]:
#convert tags from string to list
df['Tags'] = df.Tags.apply(eval)
df

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22000.0,"[219 m², 4 Pièces, 3 Chambres, 3 Salles de bai..."
1,Appartements,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"[86 m², 3 Pièces, 2 Chambres, 2 Salles de bain..."
2,Appartements,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900000.0,"[86 m², 3 Pièces, 2 Chambres, 1 Salle de bain,..."
3,Appartements,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2400000.0,"[180 m², 5 Pièces, 3 Chambres, 3 Salles de bai..."
4,Appartements,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"[120 m², 5 Pièces, 3 Chambres, 2 Salles de bai..."
...,...,...,...,...,...,...,...
3295,Villas,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"[1040 m², 8 Pièces, 5 Chambres, 6 Salles de ba..."
3296,Appartements,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"[74 m², 3 Pièces, 2 Chambres, 2 Salles de bain..."
3297,Appartements,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"[56 m², 2 Pièces, 1 Chambre, 2 Salles de bains..."
3298,Appartements,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"[68 m², 3 Pièces, 2 Chambres, 1 Salle de bain,..."
3299,Appartements,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"[230 m², 9 Pièces, 3 Chambres, 3 Salles de bai..."

In [10]:
df

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags,Area,Etat,Bedrooms,Bathrooms,Floor,Other_tags
0,Appartements,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22000.0,"[219 m², 4 Pièces, 3 Chambres, 3 Salles de bai...",219 m²,11ème étage,3 Chambres,3 Salles de bains,11ème étage,[]
1,Appartements,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"[86 m², 3 Pièces, 2 Chambres, 2 Salles de bain...",86 m²,1er étage,2 Chambres,2 Salles de bains,1er étage,[]
2,Appartements,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900000.0,"[86 m², 3 Pièces, 2 Chambres, 1 Salle de bain,...",86 m²,5ème étage,2 Chambres,1 Salle de bain,5ème étage,[]
3,Appartements,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2400000.0,"[180 m², 5 Pièces, 3 Chambres, 3 Salles de bai...",180 m²,3ème étage,3 Chambres,3 Salles de bains,3ème étage,[]
4,Appartements,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"[120 m², 5 Pièces, 3 Chambres, 2 Salles de bai...",120 m²,5ème étage,3 Chambres,2 Salles de bains,5ème étage,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,Villas,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"[1040 m², 8 Pièces, 5 Chambres, 6 Salles de ba...",1040 m²,Bon état,5 Chambres,6 Salles de bains,NaN,[]
3296,Appartements,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"[74 m², 3 Pièces, 2 Chambres, 2 Salles de bain...",74 m²,4ème étage,2 Chambres,2 Salles de bains,4ème étage,[]
3297,Appartements,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"[56 m², 2 Pièces, 1 Chambre, 2 Salles de bains...",56 m²,4ème étage,1 Chambre,2 Salles de bains,4ème étage,[]
3298,Appartements,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"[68 m², 3 Pièces, 2 Chambres, 1 Salle de bain,...",68 m²,4ème étage,2 Chambres,1 Salle de bain,4ème étage,[]
3299,Appartements,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"[230 m², 9 Pièces, 3 Chambres, 3 Salles de bai...",230 m²,6ème étage,3 Chambres,3 Salles de bains,6ème étage,[]

In [11]:
#clean area, rooms, bedrooms, bathrooms and floor columns
df['Area'] = df['Area'].str.replace(r'\D+','').astype('float')
df['Rooms'] = df['Rooms'].str.replace(r'\D+','').astype('int')
df['Bedrooms'] = df['Bedrooms'].str.replace(r'\D+','').astype('int')
df['Bathrooms'] = df['Bathrooms'].str.replace(r'\D+','').astype('int')
df['Floor'] = df['Floor'].str.replace(r'\D+','').astype('int')
df

ValueError: could not convert string to float: '219 m²'

In [ ]:
df.describe()