# Houses Cleaning notebook

In [1]:
import pandas as pd

In [3]:
# Load the uploaded file to inspect its structure
file_path = '../../casablanca_houses_data.csv'
data = pd.read_csv(file_path)
data

,Type,Localisation,Latitude,Longitude,Title,Price,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22 000 DH,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1 230 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900 000 DH,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2 400 000 DH,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1 550 000 DH,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16 000 000 DH,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1 140 000 DH,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870 000 DH,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495 000 DH,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2 760 000 DH,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [5]:
# Display basic information of the dataset
data_info = data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3300 entries, 0 to 3299
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          3286 non-null   object
 1   Localisation  3300 non-null   object
 2   Latitude      1766 non-null   float64
 3   Longitude     1766 non-null   float64
 4   Title         3300 non-null   object
 5   Price         3134 non-null   object
 6   Tags          3300 non-null   object
dtypes: float64(2), object(5)
memory usage: 180.6+ KB

In [7]:
data.isnull().sum()

Type              14
Localisation       0
Latitude        1534
Longitude       1534
Title              0
Price            166
Tags               0
dtype: int64

In [9]:
data.describe()

          Latitude    Longitude
count  1766.000000  1766.000000
mean     33.561705    -7.630379
std       0.120769     0.042762
min      32.340233    -7.857645
25%      33.559236    -7.648435
50%      33.577979    -7.636442
75%      33.588919    -7.618707
max      33.721772    -7.196045

In [11]:
# Rename the 'Price' column to 'Price in DH' after cleaning
# Clean the 'Price' column
data['Price'] = data['Price'].str.replace('DH', '').str.replace(' ', '').astype(str)
data['Price'] = pd.to_numeric(data['Price'], errors='coerce')

# Rename the column to 'Price in DH'
data.rename(columns={'Price': 'Price in DH'}, inplace=True)
data

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,NaN,NaN,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,NaN,NaN,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,NaN,NaN,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,NaN,NaN,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [13]:
data.describe()

          Latitude    Longitude   Price in DH
count  1766.000000  1766.000000  3.132000e+03
mean     33.561705    -7.630379  4.558825e+06
std       0.120769     0.042762  6.796934e+06
min      32.340233    -7.857645  1.600000e+03
25%      33.559236    -7.648435  1.250000e+06
50%      33.577979    -7.636442  2.190750e+06
75%      33.588919    -7.618707  4.800000e+06
max      33.721772    -7.196045  7.140000e+07

In [15]:
# Fill missing numeric values with the mean
numeric_columns = ['Price in DH', 'Latitude', 'Longitude']
for col in numeric_columns:
    if col in data.columns:
        data[col].fillna(data[col].mean(), inplace=True)

data

/tmp/ipykernel_54788/2756811728.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [19]:
# Fill missing non-numeric values with the mode
non_numeric_columns = ['Type']
for col in non_numeric_columns:
    if col in data.columns:
        data[col].fillna(data[col].mode()[0], inplace=True)

data

,Type,Localisation,Latitude,Longitude,Title,Price in DH,Tags
0,Appartements Casablanca,Casablanca Finance City à Casablanca,33.561705,-7.630379,Somptueux appartement à louer au tour végétal,22000.0,"['219 m²', '4 Pièces', '3 Chambres', '3 Salles..."
1,Appartements Casablanca,Anfa à Casablanca,33.561705,-7.630379,A vendre appartement 86m face ELBILIA lahjajma,1230000.0,"['86 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
2,Appartements Casablanca,La Gironde à Casablanca,33.561705,-7.630379,A vendre bel appartement 2 chambres Gironde,900000.0,"['86 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3,Appartements Casablanca,Bourgogne Ouest à Casablanca,33.561705,-7.630379,A vendre appartement 180m clinique Badr pas cher,2400000.0,"['180 m²', '5 Pièces', '3 Chambres', '3 Salles..."
4,Appartements Casablanca,Les princesses à Casablanca,33.574209,-7.644182,Appartement 3 chambres yaacoub almansour pas cher,1550000.0,"['120 m²', '5 Pièces', '3 Chambres', '2 Salles..."
...,...,...,...,...,...,...,...
3295,Villas & maisons de luxe Casablanca,Californie à Casablanca,33.535958,-7.625628,Superbe villa à vendre sur Californie,16000000.0,"['1040 m²', '8 Pièces', '5 Chambres', '6 Salle..."
3296,Appartements Casablanca,Val Fleury à Casablanca,33.574082,-7.639103,2 chambres séjour au 4ème étage orienté est ouest,1140000.0,"['74 m²', '3 Pièces', '2 Chambres', '2 Salles ..."
3297,Appartements Casablanca,Hermitage à Casablanca,33.568940,-7.615812,Magnifique studio de 56m2 sur Boulevard Anoual,870000.0,"['56 m²', '2 Pièces', '1 Chambre', '2 Salles d..."
3298,Appartements Casablanca,Hay Arrahma à Casablanca,33.598785,-7.567606,Bel appartement à vendre à résidence Almanzeh,495000.0,"['68 m²', '3 Pièces', '2 Chambres', '1 Salle d..."
3299,Appartements Casablanca,Les Hôpitaux à Casablanca,33.577979,-7.620006,Grand et lumineux appartement à Abdelmoumen,2760000.0,"['230 m²', '9 Pièces', '3 Chambres', '3 Salles..."

In [21]:
data.isnull().sum()

Type            0
Localisation    0
Latitude        0
Longitude       0
Title           0
Price in DH     0
Tags            0
dtype: int64

In [23]:
# Display unique values in the 'Type' column
unique_types = data['Type'].unique()
unique_types

array(['Appartements Casablanca', 'Villas & maisons de luxe Casablanca',
       'Riad Casablanca', 'Maisons Casablanca'], dtype=object)

In [25]:
# Display unique values in the 'Localisation' column
unique_localisations = data['Localisation'].unique()
print(unique_localisations)

['Casablanca Finance City à Casablanca' 'Anfa à Casablanca'
 'La Gironde à Casablanca' 'Bourgogne Ouest à Casablanca'
 'Les princesses à Casablanca' "Triangle d'Or à Casablanca"
 'Maârif Extension à Casablanca' 'Anassi à Casablanca'
 'Californie à Casablanca' 'Maârif à Casablanca' 'Racine à Casablanca'
 'Gauthier à Casablanca' 'Val Fleury à Casablanca'
 'Beauséjour à Casablanca' 'Riviera à Casablanca'
 'Sidi Maarouf à Casablanca' 'Ain Diab à Casablanca'
 'Racine Extension à Casablanca' 'Palmier à Casablanca'
 'El Manar - El Hank à Casablanca' 'Oasis à Casablanca'
 'Hay Lmkansa à Casablanca' 'CIL (Hay Salam) à Casablanca'
 'Les Crêtes à Casablanca' 'Les Hôpitaux à Casablanca'
 'Bourgogne Est à Casablanca' 'Ain Diab Extension à Casablanca'
 'Hay Alamal à Casablanca' 'Mers Sultan à Casablanca'
 'Laymoune à Casablanca' 'Longchamps (Hay Al Hanâa) à Casablanca'
 'Oulfa à Casablanca' 'Belvédère à Casablanca' 'Centre Ville à Casablanca'
 'Derb Ghalef à Casablanca' 'Aïn Sebaâ à Casablanca'
 'Hay Alhoda à Casablanca' 'Polo à Casablanca' 'Hay Zobir à Casablanca'
 'Casablanca' 'Foncière à Casablanca' 'Anfa Supérieur à Casablanca'
 'Ain Borja à Casablanca' 'Hermitage à Casablanca' 'Benjdia à Casablanca'
 'Ain Chock à Casablanca' 'Burger à Casablanca'
 'Plateau (Al Batha) à Casablanca'
 'Ferme Bretonne (Hay Arraha) à Casablanca'
 'Casablanca Marina à Casablanca' 'Al Hadika à Casablanca'
 'Port à Casablanca' 'Hay Moulay Rachid 1 à Casablanca'
 'Lissasfa à Casablanca' 'Al Azhar à Casablanca' 'Mandarona à Casablanca'
 'Nassim 1 à Casablanca' 'Tantonville à Casablanca'
 'Sidi Belyout à Casablanca' 'Bernoussi à Casablanca'
 'Ahl Loghlam (Hay Assalam) à Casablanca' 'Franceville à Casablanca'
 'Salmia 2 à Casablanca' 'Itissal à Casablanca'
 'Moulay Youssef à Casablanca' 'Derb Chorfa à Casablanca'
 'Derb Loubila à Casablanca' 'Sidi Moumen à Casablanca'
 'Hay Almassira 2 à Casablanca' 'Nassim 2 à Casablanca'
 'Hay Hassani à Casablanca' 'Derb Abdellah à Casablanca'
 'Roches Noires à Casablanca' 'Hay Al Qods à Casablanca'
 'Al Qods à Casablanca' 'Hay Arrahma à Casablanca'
 'Garage Allal à Casablanca' 'Sidi Othmane à Casablanca'
 'Hay Al Amal à Casablanca' 'Michouar à Casablanca'
 'Hay Inara à Casablanca' 'Hay Mansour à Casablanca'
 'Beausite à Casablanca' 'La Vilette à Casablanca'
 'Derb Moulay Cherif à Casablanca' 'Quartier Bachkou à Casablanca'
 'Hay Lalla Meriem à Casablanca' 'Hay Tasahol à Casablanca'
 "Hay M'barka à Casablanca" 'La Floride à Casablanca'
 'Hay Chrifa à Casablanca' 'Sidi El Khadir à Casablanca'
 'Hay Hakam à Casablanca' 'Derb Salama à Casablanca'
 'Derb Omar à Casablanca' 'Hay Moulay Abdellah à Casablanca'
 'Hay Mohammadi à Casablanca' 'Habbous à Casablanca'
 'Al Osra à Casablanca' 'Tacharouk (Hay Al Walaa) à Casablanca'
 'Hay Tarik à Casablanca' 'Zone Industrielle Moulay Rachid à Casablanca'
 'Al Madina Aljadida à Casablanca' 'Quartier Cheminots à Casablanca'
 'Hay Albaraka à Casablanca' 'Hay Salama à Casablanca'
 'Hay Adil à Casablanca' 'Hay Arsalan à Casablanca'
 'Al Hassania à Casablanca']